version: '3.3'
services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - db
    volumes:
      - .:/usr/src/app"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
    depends_on:
      - db
  db:
    container_name: psql
    image: postgres
    ports:
      - '5433:${DB_PORT}'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
volumes:
  data: {}
